services:
  backend:
    build: ./backend
    image: mean-starter-template
    restart: unless-stopped
    ports:
      - "3000:3000" # expose backend on localhost:3000
    volumes:
      - ./backend:/app # sync backend code for live reload
      - node_modules:/app/node_modules # keep node_modules inside container
    env_file:
      - ./backend/.env # load environment variables from .env file
    networks:
      - shared-mongo-net

networks:
  shared-mongo-net:
    external: true

volumes:
  node_modules:
